using System.Diagnostics.CodeAnalysis;
using System.Globalization;

namespace MyRPA.Core.Identifiers;

/// <summary>Identifies one execution (run) of a workflow. Always generated by MyRPA, never supplied by callers.</summary>
public sealed record ExecutionId
{
    /// <summary>Wraps an existing execution identifier value.</summary>
    /// <param name="value">A non-empty GUID.</param>
    /// <exception cref="ArgumentException"><paramref name="value"/> is <see cref="Guid.Empty"/>.</exception>
    public ExecutionId(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException("Execution id must not be empty.", nameof(value));
        }

        Value = value;
    }

    /// <summary>The identifier value.</summary>
    public Guid Value { get; }

    /// <summary>Creates a new, time-ordered (UUID v7) execution identifier.</summary>
    public static ExecutionId New() => new(Guid.CreateVersion7());

    /// <summary>Parses the text form produced by <see cref="ToString"/>.</summary>
    /// <param name="value">32 hexadecimal digits (GUID "N" format).</param>
    /// <param name="result">The identifier when valid.</param>
    public static bool TryParse(string? value, [NotNullWhen(true)] out ExecutionId? result)
    {
        result = Guid.TryParseExact(value, "N", out var guid) && guid != Guid.Empty ? new ExecutionId(guid) : null;
        return result is not null;
    }

    /// <summary>Returns the GUID in "N" format (32 hexadecimal digits, no dashes).</summary>
    public override string ToString() => Value.ToString("N", CultureInfo.InvariantCulture);
}
