using MyRPA.Contracts.Execution;
using MyRPA.Core.Identifiers;
using MyRPA.Workflow.Execution;

namespace MyRPA.Execution.Hosting;

/// <summary>
/// One run's state: its engine observer (ADR-0023), its bounded, sequenced event buffer and its cancellation. Events are
/// appended in engine order under a lock; readers wait for new events without blocking the engine.
/// </summary>
internal sealed class ExecutionRecord : IExecutionObserver, IDisposable
{
    private readonly Lock _gate = new();
    private readonly ExecutionEventMessage[] _ring;
    private int _start;
    private int _count;
    private long _last;
    private bool _completed;
    private TaskCompletionSource _changed = NewSignal();
    private volatile ExecutionRunState _state = ExecutionRunState.Queued;

    public ExecutionRecord(CorrelationId correlationId, int capacity)
    {
        CorrelationId = correlationId;
        _ring = new ExecutionEventMessage[capacity];
    }

    /// <summary>The run id (the run's correlation id, generated by the host).</summary>
    public string RunId => CorrelationId.Value;

    public CorrelationId CorrelationId { get; }

    public CancellationTokenSource Cancellation { get; } = new();

    /// <summary>Completes with the run's result (or the host failure).</summary>
    public TaskCompletionSource<WorkflowExecutionResult> Result { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

    public ExecutionRunState State => _state;

    public long LastSequence
    {
        get
        {
            lock (_gate)
            {
                return _last;
            }
        }
    }

    public bool IsCompleted
    {
        get
        {
            lock (_gate)
            {
                return _completed;
            }
        }
    }

    public void MarkRunning() => _state = ExecutionRunState.Running;

    /// <inheritdoc />
    public void OnEvent(ExecutionEvent executionEvent)
    {
        var message = Map(executionEvent);
        Append(message, final: executionEvent is ExecutionCompleted && executionEvent.ParentExecutionId is null);
    }

    /// <summary>Adds a log entry of this run (ignored once the run has completed).</summary>
    public void AppendLog(DateTimeOffset time, string level, string message, string? executionId, string? nodeId) =>
        Append(new ExecutionEventMessage { Sequence = 0, Kind = ExecutionEventKinds.Log, RunId = RunId, Time = time, Level = level, Message = message, ExecutionId = executionId, NodeId = nodeId }, final: false);

    /// <summary>
    /// Ends a run that produced no completion event of its own (cancelled while queued, or a host failure): appends the
    /// terminal event from the result.
    /// </summary>
    public void CompleteFrom(WorkflowExecutionResult result)
    {
        if (IsCompleted)
        {
            return;
        }

        Append(
            new ExecutionEventMessage
            {
                Sequence = 0,
                Kind = ExecutionEventKinds.ExecutionCompleted,
                RunId = RunId,
                Time = result.StartedAt + result.Duration,
                ExecutionId = result.ExecutionId.ToString(),
                WorkflowId = result.WorkflowId.Value,
                Status = result.Status.ToString(),
                Error = Map(result.Error),
                DurationMs = result.Duration.TotalMilliseconds,
            },
            final: true);
    }

    public void MarkCompleted() => _state = ExecutionRunState.Completed;

    /// <summary>Ends a run whose host failed unexpectedly (not a workflow failure; the engine reports those).</summary>
    public void CompleteWithHostFailure(DateTimeOffset time, string message) =>
        Append(
            new ExecutionEventMessage
            {
                Sequence = 0,
                Kind = ExecutionEventKinds.ExecutionCompleted,
                RunId = RunId,
                Time = time,
                Status = nameof(Core.Execution.ExecutionStatus.Failed),
                Error = new ExecutionErrorMessage("HostFailure", message, ErrorType: "Host"),
            },
            final: true);

    /// <summary>Events after <paramref name="after"/>, the first retained sequence, completion and a signal for more.</summary>
    public (List<ExecutionEventMessage> Events, long FirstRetained, bool Completed, Task Changed) Read(long after)
    {
        lock (_gate)
        {
            var first = _last - _count + 1;
            var skip = (int)Math.Clamp(after - first + 1, 0, _count);
            var events = new List<ExecutionEventMessage>(_count - skip);
            for (var i = skip; i < _count; i++)
            {
                events.Add(_ring[(_start + i) % _ring.Length]);
            }

            return (events, first, _completed, _changed.Task);
        }
    }

    public void Dispose() => Cancellation.Dispose();

    private void Append(ExecutionEventMessage message, bool final)
    {
        TaskCompletionSource signal;
        lock (_gate)
        {
            if (_completed)
            {
                return;
            }

            var sequenced = message with { Sequence = ++_last };
            if (_count == _ring.Length)
            {
                _start = (_start + 1) % _ring.Length;
                _count--;
            }

            _ring[(_start + _count) % _ring.Length] = sequenced;
            _count++;
            _completed = final;
            signal = _changed;
            _changed = NewSignal();
        }

        signal.TrySetResult();
    }

    private ExecutionEventMessage Map(ExecutionEvent e)
    {
        var message = new ExecutionEventMessage
        {
            Sequence = 0,
            Kind = string.Empty,
            RunId = RunId,
            Time = e.Time,
            ExecutionId = e.ExecutionId.ToString(),
            ParentExecutionId = e.ParentExecutionId?.ToString(),
        };
        return e switch
        {
            ExecutionStarted s => message with { Kind = ExecutionEventKinds.ExecutionStarted, WorkflowId = s.WorkflowId.Value },
            NodeStarted n => message with { Kind = ExecutionEventKinds.NodeStarted, NodeId = n.NodeId.Value, ActivityType = n.ActivityType.Value },
            NodeCompleted n => message with
            {
                Kind = ExecutionEventKinds.NodeCompleted,
                NodeId = n.NodeId.Value,
                ActivityType = n.ActivityType.Value,
                Status = n.Status.ToString(),
                Error = Map(n.Error),
            },
            ExecutionCompleted c => message with
            {
                Kind = ExecutionEventKinds.ExecutionCompleted,
                WorkflowId = c.WorkflowId.Value,
                Status = c.Status.ToString(),
                Error = Map(c.Error),
                DurationMs = c.Duration.TotalMilliseconds,
            },
            _ => message with { Kind = e.GetType().Name },
        };
    }

    private static ExecutionErrorMessage? Map(ExecutionError? error) =>
        error is null ? null : new ExecutionErrorMessage(error.Code, error.Message, error.NodeId, error.ActivityType, error.ErrorType);

    private static TaskCompletionSource NewSignal() => new(TaskCreationOptions.RunContinuationsAsynchronously);
}
